#!/usr/bin/env python3
"""Shared telemetry and HTTP helpers for the Strix Halo cluster tools."""

from __future__ import annotations

import glob
import json
import os
import re
import shutil
import socket
import subprocess
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen


DEFAULT_CONFIG: dict[str, Any] = {
    "role": "server",
    "local_ip": "10.200.0.1",
    "peer_ip": "10.200.0.2",
    "agent_bind": "",
    "agent_port": 8765,
    "peer_agent_url": "",
    "agent_token_file": "",
    "llama_url": "",
    "rpc_port": 50053,
    "iperf_port": 5201,
    "cluster_iface": "usb4llm0",
    "parallel_slots": 2,
    "context_per_slot": 262144,
    "native_context_per_slot": 262144,
    "context_scaling": "native",
    "yarn_rope_scale": 0.0,
    "expected_parallel_slots": 0,
    "expected_context_per_slot": 0,
    "capacity_test_input_tokens": 65536,
    "capacity_test_context_tokens": 73824,
    "capacity_test_output_tokens": 8192,
    "capacity_test_parallel_slots": 1,
    "capacity_test_safety_margin_tokens": 96,
    "capacity_test_warmup": True,
    "capacity_test_repetitions": 3,
    "metrics_db": "/var/lib/qwen-dashboard/token-rates.sqlite3",
    "iperf_duration": 10,
    "iperf_parallel": 4,
    "iperf_target_gbps": 8.0,
    "paths": ["/", "/srv/models", "/srv/llama-rpc-cache"],
    "services": [],
}

ENV_FILE = Path("/etc/qwen3d8/cluster.env")
USB4_ENV_FILE = Path("/etc/default/usb4-cluster")


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


def parse_env_file(path: str | Path) -> dict[str, str]:
    """Read the simple KEY=value files generated by the shell installers."""

    values: dict[str, str] = {}
    try:
        lines = Path(path).read_text(encoding="utf-8").splitlines()
    except OSError:
        return values

    for line in lines:
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[7:].lstrip()
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip()
        if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", key):
            continue
        if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
            value = value[1:-1]
        values[key] = value
    return values


def _as_int(value: Any, default: int) -> int:
    try:
        return int(value)
    except (TypeError, ValueError):
        return default


def _as_float(value: Any, default: float) -> float:
    try:
        return float(value)
    except (TypeError, ValueError):
        return default


def _as_bool(value: Any, default: bool) -> bool:
    if isinstance(value, bool):
        return value
    if isinstance(value, str):
        normalized = value.strip().lower()
        if normalized in {"1", "true", "yes", "on"}:
            return True
        if normalized in {"0", "false", "no", "off"}:
            return False
    return default


def _mapping(value: Any) -> dict[str, Any]:
    return value if isinstance(value, dict) else {}


def load_config(path: str | Path | None = None) -> dict[str, Any]:
    """Load dashboard settings and infer cluster values from installed state."""

    config = dict(DEFAULT_CONFIG)
    cluster_env = parse_env_file(ENV_FILE)
    usb4_env = parse_env_file(USB4_ENV_FILE)

    if cluster_env:
        config.update(
            {
                "role": cluster_env.get("NODE_ROLE", config["role"]),
                "local_ip": cluster_env.get("CLUSTER_LOCAL_IP", config["local_ip"]),
                "peer_ip": cluster_env.get("CLUSTER_PEER_IP", config["peer_ip"]),
                "rpc_port": _as_int(cluster_env.get("RPC_PORT"), config["rpc_port"]),
                "llama_port": _as_int(cluster_env.get("LLAMA_PORT"), 8081),
                "parallel_slots": _as_int(
                    cluster_env.get("PARALLEL_SLOTS"), config["parallel_slots"]
                ),
                "context_per_slot": _as_int(
                    cluster_env.get("CONTEXT_PER_SLOT"), config["context_per_slot"]
                ),
                "native_context_per_slot": _as_int(
                    cluster_env.get(
                        "NATIVE_CONTEXT_PER_SLOT",
                        config["native_context_per_slot"],
                    ),
                    config["native_context_per_slot"],
                ),
                "context_scaling": cluster_env.get(
                    "CONTEXT_SCALING", config["context_scaling"]
                ),
                "yarn_rope_scale": _as_float(
                    cluster_env.get("YARN_ROPE_SCALE"),
                    config["yarn_rope_scale"],
                ),
                "model_file": cluster_env.get("MODEL_FILE", ""),
                "model_quant": cluster_env.get("MODEL_QUANT", ""),
                "model_alias": cluster_env.get("MODEL_ALIAS", ""),
                "tensor_split": cluster_env.get("TENSOR_SPLIT", ""),
            }
        )

    if usb4_env:
        config["cluster_iface"] = usb4_env.get(
            "CLUSTER_IFACE", config["cluster_iface"]
        )
        config["iperf_port"] = _as_int(
            usb4_env.get("IPERF_PORT"), config["iperf_port"]
        )

    file_config: dict[str, Any] = {}
    if path:
        try:
            file_config = json.loads(Path(path).read_text(encoding="utf-8"))
        except FileNotFoundError:
            file_config = {}
        except (OSError, json.JSONDecodeError) as exc:
            raise ValueError(f"could not read dashboard config {path}: {exc}") from exc
        if not isinstance(file_config, dict):
            raise ValueError(f"dashboard config {path} must contain a JSON object")
        config.update(file_config)

    config["role"] = str(config.get("role", "server"))
    config["local_ip"] = str(config.get("local_ip", ""))
    config["peer_ip"] = str(config.get("peer_ip", ""))
    config["agent_port"] = _as_int(config.get("agent_port"), 8765)
    config["rpc_port"] = _as_int(config.get("rpc_port"), 50053)
    config["iperf_port"] = _as_int(config.get("iperf_port"), 5201)
    config["parallel_slots"] = _as_int(config.get("parallel_slots"), 2)
    config["context_per_slot"] = _as_int(
        config.get("context_per_slot"), 262144
    )
    config["native_context_per_slot"] = _as_int(
        config.get("native_context_per_slot"), 262144
    )
    config["context_scaling"] = str(
        config.get("context_scaling", "native")
    ).lower()
    config["yarn_rope_scale"] = _as_float(config.get("yarn_rope_scale"), 0.0)
    expected_parallel = _as_int(config.get("expected_parallel_slots"), 0)
    config["expected_parallel_slots"] = (
        expected_parallel if expected_parallel > 0 else config["parallel_slots"]
    )
    expected_context = _as_int(config.get("expected_context_per_slot"), 0)
    config["expected_context_per_slot"] = (
        expected_context if expected_context > 0 else config["context_per_slot"]
    )
    config["capacity_test_input_tokens"] = _as_int(
        config.get("capacity_test_input_tokens"), 65536
    )
    config["capacity_test_context_tokens"] = _as_int(
        config.get("capacity_test_context_tokens"), 73824
    )
    config["capacity_test_output_tokens"] = _as_int(
        config.get("capacity_test_output_tokens"), 8192
    )
    config["capacity_test_parallel_slots"] = _as_int(
        config.get("capacity_test_parallel_slots"), 1
    )
    config["capacity_test_safety_margin_tokens"] = _as_int(
        config.get("capacity_test_safety_margin_tokens"), 96
    )
    config["capacity_test_warmup"] = _as_bool(
        config.get("capacity_test_warmup"), True
    )
    config["capacity_test_repetitions"] = max(
        1, min(_as_int(config.get("capacity_test_repetitions"), 3), 10)
    )
    installed_parallel = _as_int(cluster_env.get("PARALLEL_SLOTS"), 0)
    installed_context = _as_int(cluster_env.get("CONTEXT_PER_SLOT"), 0)
    if installed_parallel > 0:
        config["installed_parallel_slots"] = installed_parallel
        config["expected_parallel_slots"] = installed_parallel
        if "capacity_test_parallel_slots" not in file_config:
            config["capacity_test_parallel_slots"] = installed_parallel
    if installed_context > 0:
        config["installed_context_per_slot"] = installed_context
        config["expected_context_per_slot"] = installed_context
        if (
            "capacity_test_context_tokens" not in file_config
            and "capacity_test_input_tokens" not in file_config
        ):
            config["capacity_test_context_tokens"] = installed_context
    installed_native_context = _as_int(
        cluster_env.get("NATIVE_CONTEXT_PER_SLOT"), 0
    )
    if installed_native_context > 0:
        config["native_context_per_slot"] = installed_native_context
    installed_scaling = cluster_env.get("CONTEXT_SCALING")
    if installed_scaling:
        config["context_scaling"] = installed_scaling.lower()
    if "YARN_ROPE_SCALE" in cluster_env:
        config["yarn_rope_scale"] = _as_float(
            cluster_env.get("YARN_ROPE_SCALE"), 0.0
        )
    config["metrics_db"] = str(config.get("metrics_db", ""))
    config["iperf_duration"] = _as_int(config.get("iperf_duration"), 10)
    config["iperf_parallel"] = _as_int(config.get("iperf_parallel"), 4)
    config["iperf_target_gbps"] = _as_float(
        config.get("iperf_target_gbps"), 8.0
    )
    config["agent_bind"] = str(
        config.get("agent_bind") or config.get("local_ip") or "127.0.0.1"
    )

    if not config.get("llama_url") and config["role"] == "server":
        config["llama_url"] = (
            f"http://127.0.0.1:{_as_int(config.get('llama_port'), 8081)}"
        )
    if (
        config["role"] == "server"
        and not config.get("peer_agent_url")
        and config.get("peer_ip")
    ):
        config["peer_agent_url"] = (
            f"http://{config['peer_ip']}:{config['agent_port']}"
        )
    if not config.get("services"):
        if config["role"] == "server":
            config["services"] = [
                "qwen3d8-server.service",
                "nginx.service",
                "comfyui.service",
            ]
        else:
            config["services"] = [
                "qwen3d8-rpc.service",
                "comfyui.service",
            ]
    if not isinstance(config["paths"], list):
        config["paths"] = list(DEFAULT_CONFIG["paths"])
    model_file = str(config.get("model_file", ""))
    model_storage = ""
    if model_file:
        model_storage = str(Path(model_file).parent.parent)
    if config["role"] == "server":
        config["paths"] = [
            path for path in config["paths"] if path != "/srv/llama-rpc-cache"
        ]
    else:
        config["paths"] = [
            path
            for path in config["paths"]
            if path not in {"/srv/models", model_storage}
        ]
        if "/srv/llama-rpc-cache" not in config["paths"]:
            config["paths"].append("/srv/llama-rpc-cache")
    if model_storage and config["role"] == "server":
        if model_storage not in config["paths"]:
            config["paths"].append(model_storage)
    return config


def read_token(path: str | Path | None) -> str:
    if not path:
        return ""
    try:
        return Path(path).read_text(encoding="utf-8").strip()
    except OSError:
        return ""


def http_json(
    url: str, timeout: float = 3.0, headers: dict[str, str] | None = None
) -> tuple[int, Any]:
    """Return (HTTP status, decoded body), including useful error bodies."""

    request = Request(url, headers=headers or {}, method="GET")
    try:
        with urlopen(request, timeout=timeout) as response:
            raw = response.read()
            if not raw:
                return int(response.status), {}
            try:
                return int(response.status), json.loads(raw.decode("utf-8"))
            except (UnicodeDecodeError, json.JSONDecodeError):
                return int(response.status), {"body": raw.decode(errors="replace")}
    except HTTPError as exc:
        try:
            raw = exc.read()
        except OSError:
            raw = b""
        finally:
            exc.close()
        try:
            body: Any = json.loads(raw.decode("utf-8")) if raw else {}
        except (UnicodeDecodeError, json.JSONDecodeError):
            body = {"body": raw.decode(errors="replace")}
        if isinstance(body, dict):
            body.setdefault("error", f"HTTP {exc.code}")
        return int(exc.code), body
    except (OSError, TimeoutError, URLError) as exc:
        return 0, {"error": str(exc)}


def http_post_json(
    url: str,
    body: dict[str, Any],
    timeout: float = 10.0,
    headers: dict[str, str] | None = None,
) -> tuple[int, Any]:
    request_headers = {"Content-Type": "application/json"}
    if headers:
        request_headers.update(headers)
    request = Request(
        url,
        data=json.dumps(body, separators=(",", ":")).encode("utf-8"),
        headers=request_headers,
        method="POST",
    )
    try:
        with urlopen(request, timeout=timeout) as response:
            raw = response.read()
            if not raw:
                return int(response.status), {}
            try:
                return int(response.status), json.loads(raw.decode("utf-8"))
            except (UnicodeDecodeError, json.JSONDecodeError):
                return int(response.status), {"body": raw.decode(errors="replace")}
    except HTTPError as exc:
        try:
            raw = exc.read()
        except OSError:
            raw = b""
        finally:
            exc.close()
        try:
            response_body: Any = json.loads(raw.decode("utf-8")) if raw else {}
        except (UnicodeDecodeError, json.JSONDecodeError):
            response_body = {"body": raw.decode(errors="replace")}
        if isinstance(response_body, dict):
            response_body.setdefault("error", f"HTTP {exc.code}")
        return int(exc.code), response_body
    except (OSError, TimeoutError, URLError) as exc:
        return 0, {"error": str(exc)}


def _read_text(path: str | Path) -> str | None:
    try:
        return Path(path).read_text(encoding="utf-8").strip()
    except OSError:
        return None


def _read_int(path: str | Path) -> int | None:
    value = _read_text(path)
    if value is None:
        return None
    try:
        return int(value)
    except ValueError:
        return None


def _read_meminfo() -> dict[str, int]:
    values: dict[str, int] = {}
    try:
        lines = Path("/proc/meminfo").read_text(encoding="ascii").splitlines()
    except OSError:
        return values
    for line in lines:
        if ":" not in line:
            continue
        key, raw = line.split(":", 1)
        fields = raw.split()
        if not fields:
            continue
        try:
            number = int(fields[0])
        except ValueError:
            continue
        values[key] = number * 1024 if len(fields) > 1 and fields[1] == "kB" else number
    return values


def collect_memory() -> dict[str, int]:
    values = _read_meminfo()
    total = values.get("MemTotal", 0)
    available = values.get("MemAvailable", values.get("MemFree", 0))
    used = max(total - available, 0)
    swap_total = values.get("SwapTotal", 0)
    swap_free = values.get("SwapFree", 0)
    return {
        "total_bytes": total,
        "available_bytes": available,
        "used_bytes": used,
        "swap_total_bytes": swap_total,
        "swap_used_bytes": max(swap_total - swap_free, 0),
    }


def _sensor_name(path: str, fallback: str) -> str:
    label = _read_text(path)
    return label or fallback


def collect_temperatures() -> list[dict[str, Any]]:
    readings: list[dict[str, Any]] = []
    seen: set[str] = set()

    for path in sorted(glob.glob("/sys/class/thermal/thermal_zone*/temp")):
        raw = _read_int(path)
        if raw is None:
            continue
        zone = Path(path).parent.name
        sensor_type = _read_text(Path(path).parent / "type") or zone
        celsius = raw / 1000 if abs(raw) > 200 else float(raw)
        readings.append(
            {
                "name": sensor_type,
                "celsius": round(celsius, 1),
                "source": path,
            }
        )
        seen.add(path)

    for path in sorted(glob.glob("/sys/class/hwmon/hwmon*/temp*_input")):
        if path in seen:
            continue
        raw = _read_int(path)
        if raw is None:
            continue
        base = Path(path).parent
        stem = Path(path).stem.removesuffix("_input")
        name = _sensor_name(base / f"{stem}_label", f"{base.name}/{stem}")
        celsius = raw / 1000 if abs(raw) > 200 else float(raw)
        readings.append(
            {
                "name": name,
                "celsius": round(celsius, 1),
                "source": path,
            }
        )
    return readings


def collect_fans() -> list[dict[str, Any]]:
    readings: list[dict[str, Any]] = []
    for path in sorted(glob.glob("/sys/class/hwmon/hwmon*/fan*_input")):
        raw = _read_int(path)
        if raw is None:
            continue
        base = Path(path).parent
        stem = Path(path).stem.removesuffix("_input")
        name = _sensor_name(base / f"{stem}_label", f"{base.name}/{stem}")
        readings.append({"name": name, "rpm": raw, "source": path})
    return readings


def collect_gpu_memory() -> dict[str, Any]:
    cards: list[dict[str, Any]] = []
    for device_path in sorted(glob.glob("/sys/class/drm/card*/device")):
        card = Path(device_path).parent.name
        values = {
            "vram_total_bytes": _read_int(Path(device_path) / "mem_info_vram_total"),
            "vram_used_bytes": _read_int(Path(device_path) / "mem_info_vram_used"),
            "gtt_total_bytes": _read_int(Path(device_path) / "mem_info_gtt_total"),
            "gtt_used_bytes": _read_int(Path(device_path) / "mem_info_gtt_used"),
        }
        if any(value is not None for value in values.values()):
            cards.append({"card": card, **values})

    pages_limit = _read_int("/sys/module/ttm/parameters/pages_limit")
    return {
        "cards": cards,
        "ttm_limit_bytes": pages_limit * 4096 if pages_limit is not None else None,
    }


def collect_disk_usage(paths: list[Any]) -> list[dict[str, Any]]:
    result: list[dict[str, Any]] = []
    for raw_path in paths:
        path = str(raw_path)
        try:
            usage = shutil.disk_usage(path)
            usage_path = path
            warning = ""
        except OSError as exc:
            candidate = Path(path)
            while not candidate.exists() and candidate.parent != candidate:
                candidate = candidate.parent
            if not candidate.exists():
                result.append({"path": path, "error": str(exc)})
                continue
            try:
                usage = shutil.disk_usage(candidate)
            except OSError as fallback_exc:
                result.append({"path": path, "error": str(fallback_exc)})
                continue
            usage_path = str(candidate)
            warning = (
                f"{path} does not exist; showing filesystem usage from {usage_path}"
            )
        result.append(
            {
                "path": path,
                "usage_path": usage_path,
                "warning": warning,
                "total_bytes": usage.total,
                "used_bytes": usage.used,
                "available_bytes": usage.free,
            }
        )
    return result


def collect_logged_users() -> dict[str, Any]:
    try:
        result = subprocess.run(
            ["who"],
            check=False,
            capture_output=True,
            text=True,
            timeout=3,
        )
    except (FileNotFoundError, OSError, subprocess.TimeoutExpired) as exc:
        return {"sessions": 0, "unique_users": 0, "error": str(exc)}

    users = []
    for line in result.stdout.splitlines():
        fields = line.split()
        if fields:
            users.append(fields[0])
    return {
        "sessions": len(users),
        "unique_users": len(set(users)),
    }


def service_state(unit: str) -> dict[str, Any]:
    if not re.fullmatch(r"[A-Za-z0-9_.@-]+", unit):
        return {"state": "invalid", "active": False}
    try:
        result = subprocess.run(
            ["systemctl", "is-active", unit],
            check=False,
            capture_output=True,
            text=True,
            timeout=3,
        )
    except (FileNotFoundError, OSError, subprocess.TimeoutExpired) as exc:
        return {"state": "unknown", "active": False, "error": str(exc)}
    state = result.stdout.strip() or "inactive"
    return {"state": state, "active": state == "active"}


def local_tcp_listener(address: str, port: int) -> tuple[bool, str]:
    try:
        result = subprocess.run(
            ["ss", "-ltn"],
            check=False,
            capture_output=True,
            text=True,
            timeout=3,
        )
    except (FileNotFoundError, OSError, subprocess.TimeoutExpired) as exc:
        return False, str(exc)
    if result.returncode != 0:
        return False, result.stderr.strip() or "ss failed"

    expected_port = str(port)
    for line in result.stdout.splitlines():
        fields = line.split()
        if len(fields) < 4:
            continue
        endpoint = fields[3]
        if not endpoint.rsplit(":", 1)[-1] == expected_port:
            continue
        endpoint_address = endpoint.rsplit(":", 1)[0].strip("[]")
        if endpoint_address in {address, "0.0.0.0", "::", "*"}:
            return True, ""
    return False, f"no local listener on {address}:{port}"


def _tcp_endpoint(value: str) -> tuple[str, str] | None:
    endpoint = value.strip()
    if endpoint.startswith("["):
        closing = endpoint.rfind("]:")
        if closing <= 1:
            return None
        return endpoint[1:closing], endpoint[closing + 2 :]

    address, separator, port = endpoint.rpartition(":")
    if not separator or not address or not port:
        return None
    return address, port


def _established_tcp_connection(
    local_address: str, peer_address: str, port: int
) -> tuple[bool, str]:
    try:
        result = subprocess.run(
            ["ss", "-Htn", "state", "established"],
            check=False,
            capture_output=True,
            text=True,
            timeout=3,
        )
    except (FileNotFoundError, OSError, subprocess.TimeoutExpired) as exc:
        return False, str(exc)
    if result.returncode != 0:
        return False, result.stderr.strip() or "ss failed"

    expected_port = str(port)
    for line in result.stdout.splitlines():
        fields = line.split()
        if len(fields) < 2:
            continue
        local_endpoint = _tcp_endpoint(fields[-2])
        peer_endpoint = _tcp_endpoint(fields[-1])
        if (
            local_endpoint
            and peer_endpoint
            and local_endpoint[0] == local_address
            and peer_endpoint == (peer_address, expected_port)
        ):
            return True, ""
    return (
        False,
        "no established TCP connection from "
        f"{local_address} to {peer_address}:{port}",
    )


def collect_network(
    config: dict[str, Any], role: str | None = None
) -> dict[str, Any]:
    iface = str(config.get("cluster_iface", ""))
    result: dict[str, Any] = {"interface": iface}
    if iface:
        result["operstate"] = _read_text(f"/sys/class/net/{iface}/operstate") or "missing"
        result["mtu"] = _read_int(f"/sys/class/net/{iface}/mtu")
        result["speed_mbps"] = _read_int(f"/sys/class/net/{iface}/speed")
    rpc_port = _as_int(config.get("rpc_port"), 50053)
    local_ip = str(config.get("local_ip", ""))
    peer_ip = str(config.get("peer_ip", ""))
    if role == "peer":
        reachable, error = local_tcp_listener(local_ip, rpc_port)
        result["rpc_reachable"] = reachable
        if error:
            result["rpc_error"] = error
    elif peer_ip:
        reachable, error = _established_tcp_connection(
            local_ip, peer_ip, rpc_port
        )
        result["rpc_reachable"] = reachable
        if error:
            result["rpc_error"] = error
    return result


def collect_llama(config: dict[str, Any]) -> dict[str, Any]:
    base_url = str(config.get("llama_url", "")).rstrip("/")
    if not base_url:
        return {"configured": False}

    result: dict[str, Any] = {"configured": True, "url": base_url}
    health_status, health_body = http_json(f"{base_url}/health", timeout=3)
    result["health"] = {"status_code": health_status, "body": health_body}
    if health_status != 200:
        result["ready"] = False
        return result

    props_status, props_body = http_json(f"{base_url}/props", timeout=5)
    if props_status == 200 and isinstance(props_body, dict):
        defaults = _mapping(props_body.get("default_generation_settings"))
        result["total_slots"] = props_body.get("total_slots")
        result["aggregate_context"] = defaults.get("n_ctx")
        result["model_path"] = props_body.get("model_path")
        result["build_info"] = props_body.get("build_info")
    else:
        result["props_error"] = props_body

    slots_status, slots_body = http_json(f"{base_url}/slots", timeout=5)
    if slots_status == 200 and isinstance(slots_body, list):
        slots = []
        for slot in slots_body:
            if not isinstance(slot, dict):
                continue
            slots.append(
                {
                    "id": slot.get("id"),
                    "n_ctx": slot.get("n_ctx"),
                    "is_processing": bool(slot.get("is_processing")),
                    "n_decoded": _mapping(slot.get("next_token")).get("n_decoded"),
                }
            )
        result["slots"] = slots
        result["active_slots"] = sum(
            1 for slot in slots if slot["is_processing"]
        )
    else:
        result["slots_error"] = slots_body

    models_status, models_body = http_json(f"{base_url}/v1/models", timeout=5)
    if models_status == 200 and isinstance(models_body, dict):
        result["models"] = [
            item.get("id")
            for item in models_body.get("data", [])
            if isinstance(item, dict) and item.get("id")
        ]
    else:
        result["models_error"] = models_body

    result["ready"] = True
    return result


def collect_node_snapshot(
    config: dict[str, Any], role: str | None = None
) -> dict[str, Any]:
    node_role = role or str(config.get("role", "unknown"))
    services = {
        str(unit): service_state(str(unit))
        for unit in config.get("services", [])
        if str(unit)
    }
    llama = collect_llama(config) if config.get("llama_url") else None
    network = collect_network(config, role=node_role)
    users = collect_logged_users()
    active_slots = None
    slot_capacity = None
    if isinstance(llama, dict):
        active_slots = llama.get("active_slots")
        slot_capacity = llama.get("total_slots")

    errors: list[str] = []
    if llama and not llama.get("ready", False):
        errors.append("llama-server is not ready")
    if node_role == "peer":
        rpc_state = services.get("qwen3d8-rpc.service", {})
        if rpc_state and not rpc_state.get("active", False):
            errors.append("qwen3d8-rpc.service is not active")
    if network.get("rpc_reachable") is False:
        errors.append(
            f"RPC endpoint is unreachable: {network.get('rpc_error', 'connection failed')}"
        )
    if network.get("operstate") not in {None, "up", "unknown"}:
        errors.append(f"{network['interface']} is {network['operstate']}")

    get_load_average = getattr(os, "getloadavg", None)
    if callable(get_load_average):
        try:
            load_average = list(get_load_average())
        except OSError:
            load_average = []
    else:
        load_average = []
    uptime_seconds = None
    uptime_text = _read_text("/proc/uptime")
    if uptime_text:
        try:
            uptime_seconds = float(uptime_text.split()[0])
        except (IndexError, ValueError):
            uptime_seconds = None

    return {
        "schema_version": 1,
        "collected_at": utc_now(),
        "hostname": socket.gethostname(),
        "role": node_role,
        "status": "healthy" if not errors else "degraded",
        "errors": errors,
        "memory": collect_memory(),
        "temperatures": collect_temperatures(),
        "fans": collect_fans(),
        "gpu_memory": collect_gpu_memory(),
        "disk": collect_disk_usage(list(config.get("paths", []))),
        "users": {
            **users,
            "active_inference": active_slots,
            "inference_capacity": slot_capacity,
            "identity_note": (
                "llama.cpp exposes active slots, not authenticated human identities"
            ),
        },
        "services": services,
        "network": network,
        "load_average": load_average,
        "uptime_seconds": uptime_seconds,
        "inference": llama,
    }


def collect_cluster_snapshots(
    config: dict[str, Any]
) -> tuple[dict[str, Any], list[str]]:
    """Collect the controller and worker snapshots for the dashboard."""

    local = collect_node_snapshot(config)
    nodes = [local]
    errors: list[str] = []
    peer_url = str(config.get("peer_agent_url", "")).rstrip("/")
    if peer_url:
        headers: dict[str, str] = {}
        token = read_token(config.get("peer_agent_token_file"))
        if token:
            headers["X-Cluster-Agent-Token"] = token
        status, body = http_json(f"{peer_url}/metrics", timeout=5, headers=headers)
        if status == 200 and isinstance(body, dict):
            nodes.append(body)
        else:
            message = body.get("error", body) if isinstance(body, dict) else body
            errors.append(f"worker agent unavailable ({status}): {message}")
            nodes.append(
                {
                    "schema_version": 1,
                    "hostname": str(config.get("peer_ip", "worker")),
                    "role": "peer",
                    "status": "unreachable",
                    "errors": [errors[-1]],
                    "memory": {},
                    "temperatures": [],
                    "fans": [],
                    "gpu_memory": {},
                    "disk": [],
                    "users": {},
                    "services": {},
                    "network": {},
                    "inference": None,
                }
            )
    else:
        errors.append("peer_agent_url is not configured")

    known_errors = set(errors)
    for node in nodes:
        if not isinstance(node, dict):
            continue
        hostname = str(node.get("hostname", node.get("role", "node")))
        node_errors = node.get("errors", [])
        if isinstance(node_errors, list):
            for node_error in node_errors:
                if isinstance(node_error, str):
                    message = f"{hostname}: {node_error}"
                    if message not in known_errors:
                        errors.append(message)
                        known_errors.add(message)
        if node.get("status") not in {None, "healthy"} and not node_errors:
            message = f"{hostname}: status={node.get('status', 'unknown')}"
            if message not in known_errors:
                errors.append(message)
                known_errors.add(message)

    active_users = 0
    capacity = 0
    for node in nodes:
        if not isinstance(node, dict):
            continue
        users = _mapping(node.get("users"))
        active = users.get("active_inference")
        node_capacity = users.get("inference_capacity")
        if isinstance(active, int):
            active_users += active
        if isinstance(node_capacity, int):
            capacity += node_capacity

    cluster = {
        "collected_at": utc_now(),
        "status": (
            "healthy"
            if not errors and all(node.get("status") == "healthy" for node in nodes)
            else "degraded"
        ),
        "active_inference_users": active_users,
        "inference_capacity": capacity or None,
        "nodes": nodes,
        "errors": errors,
    }
    return cluster, errors


def format_bytes(value: Any) -> str:
    try:
        number = float(value)
    except (TypeError, ValueError):
        return "n/a"
    if number < 1024:
        return f"{number:.0f} B"
    units = ("KiB", "MiB", "GiB", "TiB")
    for unit in units:
        number /= 1024
        if number < 1024 or unit == units[-1]:
            return f"{number:.1f} {unit}"
    return "n/a"


def format_temperature(readings: Any) -> str:
    if not isinstance(readings, list) or not readings:
        return "n/a"
    values = [
        item.get("celsius")
        for item in readings
        if isinstance(item, dict) and isinstance(item.get("celsius"), (int, float))
    ]
    if not values:
        return "n/a"
    return f"{max(values):.1f} C max"


def format_fans(readings: Any) -> str:
    if not isinstance(readings, list) or not readings:
        return "n/a"
    values = [
        item.get("rpm")
        for item in readings
        if isinstance(item, dict) and isinstance(item.get("rpm"), (int, float))
    ]
    if not values:
        return "n/a"
    return ", ".join(f"{int(value)} RPM" for value in values)
